/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/applicant/dashboard': RouteRecordInfo<'/applicant/dashboard', '/applicant/dashboard', Record<never, never>, Record<never, never>>,
    '/authentication/login': RouteRecordInfo<'/authentication/login', '/authentication/login', Record<never, never>, Record<never, never>>,
    '/authentication/register': RouteRecordInfo<'/authentication/register', '/authentication/register', Record<never, never>, Record<never, never>>,
    '/recruiter/dashboard': RouteRecordInfo<'/recruiter/dashboard', '/recruiter/dashboard', Record<never, never>, Record<never, never>>,
    '/recruiter/job-detail': RouteRecordInfo<'/recruiter/job-detail', '/recruiter/job-detail', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/applicant/dashboard.vue': {
      routes: '/applicant/dashboard'
      views: never
    }
    'src/pages/authentication/login.vue': {
      routes: '/authentication/login'
      views: never
    }
    'src/pages/authentication/register.vue': {
      routes: '/authentication/register'
      views: never
    }
    'src/pages/recruiter/dashboard.vue': {
      routes: '/recruiter/dashboard'
      views: never
    }
    'src/pages/recruiter/job-detail.vue': {
      routes: '/recruiter/job-detail'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
